add better configuration

diff --git a/torctl b/torctl
--- a/torctl
+++ b/torctl
@@ -14,7 +14,7 @@
 ################################################################################
 
 # torctl.sh version
-VERSION="torctl.sh v0.1"
+VERSION="torctl.sh v0.2"
 
 # exclude locals
 TOR_EXCLUDE="192.168.0.0/16 172.16.0.0/12 10.0.0.0/8"
@@ -25,6 +25,8 @@ TOR_UID="tor"
 # tor socks port
 TOR_PORT="9040"
 
+# tor dns port
+TOR_DNS="9053"
 
 # colors
 GREEN="$(tput setaf 2)"
@@ -89,12 +91,26 @@ start()
 {
   # check if root
   checkroot
+
+  # generate new torrc
+  gentorrc
+
   if [[ $(systemctl is-active tor) != "active" ]]; then
     warn "tor is not started"
-	info "starting tor"
+	info "starting tor service"
 	systemctl start tor || err "unable to start tor service"
     msg "started tor service"
+  else
+    warn "tor is running"
+    info "reloading tor service"
+    systemctl reload tor || err "unable to reload tor service"
+    msg "reloaded tor service"
   fi
+
+  info "backing up nameservers"
+  mv /etc/resolv.conf /etc/resolv.conf.bak
+  echo -e '# generated by torctl\nnameserver 127.0.0.1\nnameserver 1.1.1.1\nnameserver 1.0.0.1' > /etc/resolv.conf;
+  msg "backed up nameservers"
 
   if ! [ -f /tmp/iptables.rules ]; then
       info "backing up iptables rules"
@@ -115,9 +131,9 @@ start()
   # set iptables nat
   iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
   # set dns redirect
-  iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 5353
-  iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports 5353
-  iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports 5353
+  iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports $TOR_DNS
+  iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports $TOR_DNS
+  iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports $TOR_DNS
 
   # resolve .onion domains mapping 10.192.0.0/10 address space
   iptables -t nat -A OUTPUT -p tcp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
@@ -157,6 +173,20 @@ stop()
       msg "restored iptables rules"
   fi
 
+  if [ -e /etc/resolv.conf.bak ]; then
+      warn "restoring nameservers"
+      rm /etc/resolv.conf
+      mv /etc/resolv.conf.bak /etc/resolv.conf
+      msg "restored nameservers"
+  fi
+
+  if [ -e /etc/tor/torrc.bak ]; then
+      warn "restoring tor config"
+      rm /etc/tor/torrc
+      mv /etc/tor/torrc.bak /etc/tor/torrc
+      msg "restored tor config"
+  fi
+
   # enable ipv6
   info "enabling ipv6"
   sysctl -w net.ipv6.conf.all.disable_ipv6=0 > "/dev/null"
@@ -181,24 +211,43 @@ status()
   info "tor service is: ${TORSTATUS}"
 }
 
-init()
+gentorrc()
 {
   checkroot
   TORRC="/etc/tor/torrc"
-  TORRCRULES="\n# added by torctl\nVirtualAddrNetwork 10.192.0.0/10\nAutomapHostsOnResolve 1\nTransPort 9040\nDNSPort 5353"
-  warn "initializing torrc"
-  cp "$TORRC" "$TORRC.bak"
-  echo -e "${TORRCRULES}" >> "$TORRC"
-  msg "initialized torrc"
-  systemctl restart tor
+  warn "backing up tor config"
+  mv "$TORRC" "$TORRC.bak"
+  cat > "${TORRC}" << EOF
+# generated by torctl
+DataDirectory /var/lib/tor
+VirtualAddrNetwork 10.192.0.0/10
+AutomapHostsOnResolve 1
+AutomapHostsSuffixes .exit,.onion
+TransPort 127.0.0.1:$TOR_PORT IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
+SocksPort 127.0.0.1:9050 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
+ControlPort 9051
+HashedControlPassword 16:FDE8ED505C45C8BA602385E2CA5B3250ED00AC0920FEC1230813A1F86F
+DNSPort 127.0.0.1:$TOR_DNS
+HardwareAccel 1
+TestSocks 1
+AllowNonRFC953Hostnames 0
+WarnPlaintextPorts 23,109,110,143,80
+ClientRejectInternalAddresses 1
+NewCircuitPeriod 40
+MaxCircuitDirtiness 600
+MaxClientCircuitsPending 48
+UseEntryGuards 1
+EnforceDistinctSubnets 1
+EOF
+  chmod 644 ${TORRC}
+  msg "backed up tor config"
 }
 
 usage()
 {
   echo -e "usage:\n"
-  echo -e "  torctl.sh init | start | stop | status | restart | ip | change | version\n"
+  echo -e "  torctl.sh start | stop | status | restart | ip | change | version\n"
   echo -e "options:\n"
-  echo -e "  init    - initialize and start tor"
   echo -e "  start   - start tor and redirect all traffic through tor"
   echo -e "  stop    - stop tor and redirect all traffic through clearnet"
   echo -e "  status  - get tor service status"
@@ -212,10 +261,6 @@ main()
 {
   banner
   case "$1" in
-      init)
-          init
-          start
-          ;;
       start)
           start
           ;;
@@ -232,9 +277,9 @@ main()
           ip
           ;;
       restart)
-          $0 stop
+          stop
           sleep 1
-          $0 start
+          start
           ;;
       version)
           version
