add start and stop checks and change mac

diff --git a/torctl b/torctl
--- a/torctl
+++ b/torctl
@@ -15,7 +15,7 @@
 ################################################################################
 
 # torctl.sh version
-VERSION="torctl.sh v0.5.1"
+VERSION="torctl.sh v0.5.2"
 
 # exclude locals
 TOR_EXCLUDE="192.168.0.0/16 172.16.0.0/12 10.0.0.0/8"
@@ -30,20 +30,40 @@ TOR_PORT="9040"
 TOR_DNS="9053"
 
 # colors
+GREEN=""
+RED=""
+REDB=""
+YELLOW=""
+BLUE=""
+RESET=""
+
 if [ -t 1 ];then
-    GREEN="$(tput setaf 2)"
-    RED="$(tput setaf 1)"
-    REDB="$(tput bold; tput setaf 1)"
-    YELLOW="$(tput setaf 3)"
-    BLUE="$(tput setaf 4)"
-    NC="$(tput sgr0)"
+    if tput setaf 0 &>/dev/null; then
+        RESET="$(tput sgr0)"
+        BOLD="$(tput bold)"
+        GREEN="$(tput setaf 2)"
+        RED="$(tput setaf 1)"
+        REDB="${BOLD}${RED}"
+        YELLOW="$(tput setaf 3)"
+        BLUE="$(tput setaf 4)"
+    else
+        RESET="\e[0m"
+        BOLD="\e[1m"
+        GREEN="\e[32m"
+        RED="\e[31m"
+        REDB="${BOLD}${RED}"
+        YELLOW="\e[33m"
+        BLUE="\e[34m"
+    fi
 fi
 
+# backup dir
+BACKUPDIR="/tmp/torctl"
 
 # print error and exit
 err()
 {
-    echo "${RED}[-]${NC} ERROR: ${@}"
+    echo "${RED}[-]${RESET} ERROR: ${@}"
     exit 1
 }
 
@@ -51,24 +71,24 @@ err()
 # print warning
 warn()
 {
-    echo "${YELLOW}[!]${NC} WARNING: ${@}"
+    echo "${YELLOW}[!]${RESET} WARNING: ${@}"
 }
 
 # print message
 msg()
 {
-    echo "${GREEN}[+]${NC} ${@}"
+    echo "${GREEN}[+]${RESET} ${@}"
 }
 
 # print info
 info()
 {
-    echo "${BLUE}[*]${NC} ${@}"
+    echo "${BLUE}[*]${RESET} ${@}"
 }
 
 banner()
 {
-    echo -e "${REDB}--==[ torctl.sh by blackarch.org ]==--${NC}\n"
+    echo -e "${REDB}--==[ torctl.sh by blackarch.org ]==--${RESET}\n"
 }
 
 version()
@@ -83,15 +103,61 @@ checkroot()
     fi
 }
 
+getiface()
+{
+    echo $(echo ${@} | awk -F"dev " 'NR==1{split($2,a," ");print a[1]}')
+}
+
+getmac()
+{
+    echo $(cat /sys/class/net/${@}/address)
+}
+
+startservice()
+{
+    SERVICE=${@}
+    if [[ $(systemctl is-active $SERVICE) != "active" ]]; then
+        warn "$SERVICE is not started"
+        info "starting $SERVICE service"
+        systemctl start $SERVICE || err "unable to start $SERVICE service"
+        msg "started $SERVICE service"
+    else
+        warn "$SERVICE is running"
+        info "reloading $SERVICE service"
+        systemctl reload $SERVICE || err "unable to reload $SERVICE service"
+        msg "reloaded $SERVICE service"
+    fi
+
+}
+
+stopservice()
+{
+    SERVICE=${@}
+    if [[ $(systemctl is-active $SERVICE) == "active" ]]; then
+        warn "$SERVICE is active"
+        info "stopping $SERVICE service"
+        systemctl stop $SERVICE || err "unable to stop $SERVICE service"
+        msg "stopped $SERVICE service"
+    fi
+}
+
 sysinfo()
 {
     LADDR=$(ip route get 1.1.1.1)
     LSRC=$(echo $LADDR | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')
-    IFACE=$(echo $LADDR | awk -F"dev " 'NR==1{split($2,a," ");print a[1]}')
-    MAC=$(cat /sys/class/net/$IFACE/address)
+    IFACE=$(getiface $LADDR)
+    MAC=$(getmac $IFACE)
     RADDR=$(wget -qO- http://ipecho.net/plain)
     msg "local ip: $LSRC (IFACE: $IFACE, MAC: $MAC)"
     msg "remote ip: $RADDR"
+}
+
+is-started()
+{
+    if [ -e $BACKUPDIR/started ];then
+        return 0
+    fi
+    return 1
 }
 
 start()
@@ -99,31 +165,26 @@ start()
     # check if root
     checkroot
 
+    # check if started
+    if is-started; then
+        err "torctl is already started"
+    fi
+
     # generate new torrc
     gentorrc
 
-    if [[ $(systemctl is-active tor) != "active" ]]; then
-        warn "tor is not started"
-        info "starting tor service"
-        systemctl start tor || err "unable to start tor service"
-        msg "started tor service"
-    else
-        warn "tor is running"
-        info "reloading tor service"
-        systemctl reload tor || err "unable to reload tor service"
-        msg "reloaded tor service"
-    fi
+    # start needed services
+    startservice iptables
+    startservice tor
 
     info "backing up nameservers"
-    mv /etc/resolv.conf /etc/resolv.conf.bak
+    mv /etc/resolv.conf $BACKUPDIR/resolv.conf.bak
     echo -e '# generated by torctl\nnameserver 127.0.0.1\nnameserver 1.1.1.1\nnameserver 1.0.0.1' > /etc/resolv.conf;
     msg "backed up nameservers"
 
-    if ! [ -f /tmp/iptables.rules ]; then
-        info "backing up iptables rules"
-        iptables-save > /tmp/iptables.rules
-        msg "backed up iptables rules"
-    fi
+    info "backing up iptables rules"
+    iptables-save > $BACKUPDIR/iptables.rules.bak
+    msg "backed up iptables rules"
 
     iptables -F
     iptables -t nat -F
@@ -163,6 +224,8 @@ start()
     iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
     iptables -A OUTPUT -j REJECT
     msg "all traffic is being redirected through tor"
+
+    touch $BACKUPDIR/started
 }
 
 
@@ -171,26 +234,31 @@ stop()
     # check if root
     checkroot
 
+    # check if stopped
+    if ! is-started; then
+        err "torctl is already stopped"
+    fi
+
     iptables -F
     iptables -t nat -F
-    if [ -f /tmp/iptables.rules ]; then
+    if [ -f $BACKUPDIR/iptables.rules.bak ]; then
         warn "restoring iptables rules"
-        iptables-restore < /tmp/iptables.rules
-        rm /tmp/iptables.rules
+        iptables-restore < $BACKUPDIR/iptables.rules.bak
+        rm -f $BACKUPDIR/iptables.rules.bak
         msg "restored iptables rules"
     fi
 
-    if [ -e /etc/resolv.conf.bak ]; then
+    if [ -e $BACKUPDIR/resolv.conf.bak ]; then
         warn "restoring nameservers"
-        rm /etc/resolv.conf
-        mv /etc/resolv.conf.bak /etc/resolv.conf
+        rm -f $BACKUPDIR/resolv.conf
+        mv $BACKUPDIR/resolv.conf.bak /etc/resolv.conf
         msg "restored nameservers"
     fi
 
-    if [ -e /etc/tor/torrc.bak ]; then
+    if [ -e $BACKUPDIR/torrc.bak ]; then
         warn "restoring tor config"
-        rm /etc/tor/torrc
-        mv /etc/tor/torrc.bak /etc/tor/torrc
+        rm -f /etc/tor/torrc
+        mv $BACKUPDIR/torrc.bak /etc/tor/torrc
         msg "restored tor config"
     fi
 
@@ -198,16 +266,37 @@ stop()
     info "enabling ipv6"
     sysctl -w net.ipv6.conf.all.disable_ipv6=0 > "/dev/null"
     sysctl -w net.ipv6.conf.default.disable_ipv6=0 > "/dev/null"
-    systemctl stop tor
+    stopservice tor
+
+    rm -f $BACKUPDIR/started
 }
 
 
-change()
+chngid()
 {
+    # check if root
     checkroot
+
+    # check if stopped
+    if ! is-started; then
+        err "torctl is stopped"
+    fi
+
     info "changing tor identity"
-    systemctl restart tor > "/dev/null"
+    stopservice tor > "/dev/null"
+    sleep 1
+    startservice tor > "/dev/null"
     msg "tor identity changed"
+}
+
+chngmac()
+{
+    LADDR=$(ip route get 1.1.1.1)
+    IFACE=$(getiface $LADDR)
+    echo $IFACE
+    ifconfig $IFACE down
+    macchanger -r $IFACE > "/dev/null"
+    ifconfig $IFACE up
 }
 
 
@@ -239,7 +328,7 @@ gentorrc()
     checkroot
     TORRC="/etc/tor/torrc"
     warn "backing up tor config"
-    mv "$TORRC" "$TORRC.bak"
+    mv "$TORRC" $BACKUPDIR/torrc.bak
     cat > "${TORRC}" << EOF
 # generated by torctl
 DataDirectory /var/lib/tor
@@ -292,6 +381,14 @@ autostart()
     systemctl enable torctl-autostart > "/dev/null"
     msg "enabled torctl-autostart"
 }
+
+checkbackupdir()
+{
+    if [ ! -d $BACKUPDIR ]; then
+        mkdir -p $BACKUPDIR
+    fi
+}
+
 usage()
 {
     echo -e "Usage: torctl.sh COMMAND\n"
@@ -304,13 +401,15 @@ usage()
     echo -e "  memwipe    - enable memory wipe at shutdown"
     echo -e "  autostart  - start torctl at startup"
     echo -e "  info       - get network information"
-    echo -e "  change     - change tor identity"
+    echo -e "  chngid     - change tor identity"
+    echo -e "  chngmac    - change active iface's mac (this will reset the iface)"
     echo -e "  version    - print version of torctl and exit\n"
 }
 
 main()
 {
     banner
+    checkbackupdir
     case "$1" in
         start)
             start
@@ -335,8 +434,11 @@ main()
         info)
             sysinfo
         ;;
-        change)
-            change
+        chngid)
+            chngid
+        ;;
+        chngmac)
+            chngmac
         ;;
         version)
             version
