fix systemd tput error and indentation

diff --git a/torctl b/torctl
--- a/torctl
+++ b/torctl
@@ -15,7 +15,7 @@
 ################################################################################
 
 # torctl.sh version
-VERSION="torctl.sh v0.5"
+VERSION="torctl.sh v0.5.1"
 
 # exclude locals
 TOR_EXCLUDE="192.168.0.0/16 172.16.0.0/12 10.0.0.0/8"
@@ -30,203 +30,217 @@ TOR_PORT="9040"
 TOR_DNS="9053"
 
 # colors
-GREEN="$(tput setaf 2)"
-RED="$(tput setaf 1)"
-REDB="$(tput bold; tput setaf 1)"
-YELLOW="$(tput setaf 3)"
-BLUE="$(tput setaf 4)"
-NC="$(tput sgr0)"
+if [ -t 1 ];then
+    GREEN="$(tput setaf 2)"
+    RED="$(tput setaf 1)"
+    REDB="$(tput bold; tput setaf 1)"
+    YELLOW="$(tput setaf 3)"
+    BLUE="$(tput setaf 4)"
+    NC="$(tput sgr0)"
+fi
 
 
 # print error and exit
 err()
 {
-  echo "${RED}[-]${NC} ERROR: ${@}"
-  exit 1
+    echo "${RED}[-]${NC} ERROR: ${@}"
+    exit 1
 }
 
 
 # print warning
 warn()
 {
-  echo "${YELLOW}[!]${NC} WARNING: ${@}"
+    echo "${YELLOW}[!]${NC} WARNING: ${@}"
 }
 
 # print message
 msg()
 {
-  echo "${GREEN}[+]${NC} ${@}"
+    echo "${GREEN}[+]${NC} ${@}"
 }
 
 # print info
 info()
 {
-  echo "${BLUE}[*]${NC} ${@}"
+    echo "${BLUE}[*]${NC} ${@}"
 }
 
 banner()
 {
-  echo -e "${REDB}--==[ torctl.sh by blackarch.org ]==--${NC}\n"
+    echo -e "${REDB}--==[ torctl.sh by blackarch.org ]==--${NC}\n"
 }
 
 version()
 {
-  echo "${VERSION}"
+    echo "${VERSION}"
 }
 
 checkroot()
 {
-  if [ $(id -u) -ne 0 ]; then
-      err "This script must be run as root"
-  fi
+    if [ $(id -u) -ne 0 ]; then
+        err "This script must be run as root"
+    fi
 }
 
 sysinfo()
 {
-  LADDR=$(ip route get 1.1.1.1)
-  LSRC=$(echo $LADDR | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')
-  IFACE=$(echo $LADDR | awk -F"dev " 'NR==1{split($2,a," ");print a[1]}')
-  MAC=$(cat /sys/class/net/$IFACE/address)
-  RADDR=$(wget -qO- http://ipecho.net/plain)
-  msg "local ip: $LSRC (IFACE: $IFACE, MAC: $MAC)"
-  msg "remote ip: $RADDR"
+    LADDR=$(ip route get 1.1.1.1)
+    LSRC=$(echo $LADDR | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')
+    IFACE=$(echo $LADDR | awk -F"dev " 'NR==1{split($2,a," ");print a[1]}')
+    MAC=$(cat /sys/class/net/$IFACE/address)
+    RADDR=$(wget -qO- http://ipecho.net/plain)
+    msg "local ip: $LSRC (IFACE: $IFACE, MAC: $MAC)"
+    msg "remote ip: $RADDR"
 }
 
 start()
 {
-  # check if root
-  checkroot
+    # check if root
+    checkroot
 
-  # generate new torrc
-  gentorrc
+    # generate new torrc
+    gentorrc
 
-  if [[ $(systemctl is-active tor) != "active" ]]; then
-    warn "tor is not started"
-	info "starting tor service"
-	systemctl start tor || err "unable to start tor service"
-    msg "started tor service"
-  else
-    warn "tor is running"
-    info "reloading tor service"
-    systemctl reload tor || err "unable to reload tor service"
-    msg "reloaded tor service"
-  fi
+    if [[ $(systemctl is-active tor) != "active" ]]; then
+        warn "tor is not started"
+        info "starting tor service"
+        systemctl start tor || err "unable to start tor service"
+        msg "started tor service"
+    else
+        warn "tor is running"
+        info "reloading tor service"
+        systemctl reload tor || err "unable to reload tor service"
+        msg "reloaded tor service"
+    fi
 
-  info "backing up nameservers"
-  mv /etc/resolv.conf /etc/resolv.conf.bak
-  echo -e '# generated by torctl\nnameserver 127.0.0.1\nnameserver 1.1.1.1\nnameserver 1.0.0.1' > /etc/resolv.conf;
-  msg "backed up nameservers"
+    info "backing up nameservers"
+    mv /etc/resolv.conf /etc/resolv.conf.bak
+    echo -e '# generated by torctl\nnameserver 127.0.0.1\nnameserver 1.1.1.1\nnameserver 1.0.0.1' > /etc/resolv.conf;
+    msg "backed up nameservers"
 
-  if ! [ -f /tmp/iptables.rules ]; then
-      info "backing up iptables rules"
-      iptables-save > /tmp/iptables.rules
-      msg "backed up iptables rules"
-  fi
+    if ! [ -f /tmp/iptables.rules ]; then
+        info "backing up iptables rules"
+        iptables-save > /tmp/iptables.rules
+        msg "backed up iptables rules"
+    fi
 
-  iptables -F
-  iptables -t nat -F
+    iptables -F
+    iptables -t nat -F
 
-  # disable ipv6
-  info "disabling ipv6"
-  sysctl -w net.ipv6.conf.all.disable_ipv6=1 > "/dev/null"
-  sysctl -w net.ipv6.conf.default.disable_ipv6=1 > "/dev/null"
-  msg "disabled ipv6"
+    # disable ipv6
+    info "disabling ipv6"
+    sysctl -w net.ipv6.conf.all.disable_ipv6=1 > "/dev/null"
+    sysctl -w net.ipv6.conf.default.disable_ipv6=1 > "/dev/null"
+    msg "disabled ipv6"
 
-  info "redirecting all traffic through tor"
-  # set iptables nat
-  iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
-  # set dns redirect
-  iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports $TOR_DNS
-  iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports $TOR_DNS
-  iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports $TOR_DNS
+    info "redirecting all traffic through tor"
+    # set iptables nat
+    iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
+    # set dns redirect
+    iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports $TOR_DNS
+    iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports $TOR_DNS
+    iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports $TOR_DNS
 
-  # resolve .onion domains mapping 10.192.0.0/10 address space
-  iptables -t nat -A OUTPUT -p tcp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
-  iptables -t nat -A OUTPUT -p udp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
-  # exclude locals
-  for NET in $TOR_EXCLUDE 127.0.0.0/9 127.128.0.0/10; do
-      iptables -t nat -A OUTPUT -d $NET -j RETURN
-      iptables -A OUTPUT -d "$NET" -j ACCEPT
-  done
+    # resolve .onion domains mapping 10.192.0.0/10 address space
+    iptables -t nat -A OUTPUT -p tcp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
+    iptables -t nat -A OUTPUT -p udp -d 10.192.0.0/10 -j REDIRECT --to-ports $TOR_PORT
+    # exclude locals
+    for NET in $TOR_EXCLUDE 127.0.0.0/9 127.128.0.0/10; do
+        iptables -t nat -A OUTPUT -d $NET -j RETURN
+        iptables -A OUTPUT -d "$NET" -j ACCEPT
+    done
 
-  # redirect all other output through tor
-  iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TOR_PORT
-  iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports $TOR_PORT
-  iptables -t nat -A OUTPUT -p icmp -j REDIRECT --to-ports $TOR_PORT
+    # redirect all other output through tor
+    iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TOR_PORT
+    iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports $TOR_PORT
+    iptables -t nat -A OUTPUT -p icmp -j REDIRECT --to-ports $TOR_PORT
 
-  # accept already established connections
-  iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
+    # accept already established connections
+    iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
 
-  # allow only tor output
-  iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
-  iptables -A OUTPUT -j REJECT
-  msg "all traffic is being redirected through tor"
+    # allow only tor output
+    iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
+    iptables -A OUTPUT -j REJECT
+    msg "all traffic is being redirected through tor"
 }
 
 
 stop()
 {
-  # check if root
-  checkroot
+    # check if root
+    checkroot
 
-  iptables -F
-  iptables -t nat -F
-  if [ -f /tmp/iptables.rules ]; then
-      warn "restoring iptables rules"
-      iptables-restore < /tmp/iptables.rules
-      rm /tmp/iptables.rules
-      msg "restored iptables rules"
-  fi
+    iptables -F
+    iptables -t nat -F
+    if [ -f /tmp/iptables.rules ]; then
+        warn "restoring iptables rules"
+        iptables-restore < /tmp/iptables.rules
+        rm /tmp/iptables.rules
+        msg "restored iptables rules"
+    fi
 
-  if [ -e /etc/resolv.conf.bak ]; then
-      warn "restoring nameservers"
-      rm /etc/resolv.conf
-      mv /etc/resolv.conf.bak /etc/resolv.conf
-      msg "restored nameservers"
-  fi
+    if [ -e /etc/resolv.conf.bak ]; then
+        warn "restoring nameservers"
+        rm /etc/resolv.conf
+        mv /etc/resolv.conf.bak /etc/resolv.conf
+        msg "restored nameservers"
+    fi
 
-  if [ -e /etc/tor/torrc.bak ]; then
-      warn "restoring tor config"
-      rm /etc/tor/torrc
-      mv /etc/tor/torrc.bak /etc/tor/torrc
-      msg "restored tor config"
-  fi
+    if [ -e /etc/tor/torrc.bak ]; then
+        warn "restoring tor config"
+        rm /etc/tor/torrc
+        mv /etc/tor/torrc.bak /etc/tor/torrc
+        msg "restored tor config"
+    fi
 
-  # enable ipv6
-  info "enabling ipv6"
-  sysctl -w net.ipv6.conf.all.disable_ipv6=0 > "/dev/null"
-  sysctl -w net.ipv6.conf.default.disable_ipv6=0 > "/dev/null"
-  systemctl stop tor
+    # enable ipv6
+    info "enabling ipv6"
+    sysctl -w net.ipv6.conf.all.disable_ipv6=0 > "/dev/null"
+    sysctl -w net.ipv6.conf.default.disable_ipv6=0 > "/dev/null"
+    systemctl stop tor
 }
 
 
 change()
 {
-  checkroot
-  info "changing tor identity"
-  systemctl restart tor > "/dev/null"
-  msg "tor identity changed"
+    checkroot
+    info "changing tor identity"
+    systemctl restart tor > "/dev/null"
+    msg "tor identity changed"
 }
 
 
 status()
 {
-  checkroot
-  TORSTATUS=$(systemctl is-active tor)
-  MEMWIPESTATUS=$(systemctl is-enabled torctl-memwipe)
-  AUTOSTARTSTATUS=$(systemctl is-enabled torctl-autostart)
-  info "tor service is: ${TORSTATUS}"
-  info "torctl-memwipe service is: ${MEMWIPESTATUS}"
-  info "torctl-autostart service is: ${AUTOSTARTSTATUS}"
+    checkroot
+    TORSTATUS=$(systemctl is-active tor)
+    MEMWIPESTATUS=$(systemctl is-enabled torctl-memwipe)
+    AUTOSTARTSTATUS=$(systemctl is-enabled torctl-autostart)
+    if [[ "${TORSTATUS}" == "active" ]];then
+        msg "tor service is: ${TORSTATUS}"
+    else
+        warn "tor service is: ${TORSTATUS}"
+    fi
+    if [[ "${MEMWIPESTATUS}" == "enabled" ]];then
+        msg "torctl-memwipe service is: ${MEMWIPESTATUS}"
+    else
+        warn "torctl-memwipe service is: ${MEMWIPESTATUS}"
+    fi
+    if [[ "${AUTOSTARTSTATUS}" == "enabled" ]];then
+        msg "torctl-autostart service is: ${AUTOSTARTSTATUS}"
+    else
+        warn "torctl-autostart service is: ${AUTOSTARTSTATUS}"
+    fi
 }
 
 gentorrc()
 {
-  checkroot
-  TORRC="/etc/tor/torrc"
-  warn "backing up tor config"
-  mv "$TORRC" "$TORRC.bak"
-  cat > "${TORRC}" << EOF
+    checkroot
+    TORRC="/etc/tor/torrc"
+    warn "backing up tor config"
+    mv "$TORRC" "$TORRC.bak"
+    cat > "${TORRC}" << EOF
 # generated by torctl
 DataDirectory /var/lib/tor
 VirtualAddrNetwork 10.192.0.0/10
@@ -248,94 +262,94 @@ MaxClientCircuitsPending 48
 UseEntryGuards 1
 EnforceDistinctSubnets 1
 EOF
-  chmod 644 ${TORRC}
-  msg "backed up tor config"
+    chmod 644 ${TORRC}
+    msg "backed up tor config"
 }
 
 memwipe()
 {
-  checkroot
-  warn "enabling torctl-memwipe"
-  systemctl enable torctl-memwipe > "/dev/null"
-  msg "enabled torctl-memwipe"
+    checkroot
+    warn "enabling torctl-memwipe"
+    systemctl enable torctl-memwipe > "/dev/null"
+    msg "enabled torctl-memwipe"
 }
 
 wipe()
 {
-  checkroot
-  echo 1024 > /proc/sys/vm/min_free_kbytes
-  echo 3  > /proc/sys/vm/drop_caches
-  echo 1  > /proc/sys/vm/oom_kill_allocating_task
-  echo 1  > /proc/sys/vm/overcommit_memory
-  echo 0 > /proc/sys/vm/oom_dump_tasks
-  smem-secure-delete -fllv
+    checkroot
+    echo 1024 > /proc/sys/vm/min_free_kbytes
+    echo 3  > /proc/sys/vm/drop_caches
+    echo 1  > /proc/sys/vm/oom_kill_allocating_task
+    echo 1  > /proc/sys/vm/overcommit_memory
+    echo 0 > /proc/sys/vm/oom_dump_tasks
+    smem-secure-delete -fllv
 }
 
 autostart()
 {
-  checkroot
-  warn "enabling torctl-autostart"
-  systemctl enable torctl-autostart > "/dev/null"
-  msg "enabled torctl-autostart"
+    checkroot
+    warn "enabling torctl-autostart"
+    systemctl enable torctl-autostart > "/dev/null"
+    msg "enabled torctl-autostart"
 }
 usage()
 {
-  echo -e "Usage: torctl.sh COMMAND\n"
-  echo -e "A script to redirect all traffic through tor network\n"
-  echo -e "Commands:"
-  echo -e "  start      - start tor and redirect all traffic through tor"
-  echo -e "  stop       - stop tor and redirect all traffic through clearnet"
-  echo -e "  status     - get tor service status"
-  echo -e "  restart    - restart tor and traffic rules"
-  echo -e "  memwipe    - enable memory wipe at shutdown"
-  echo -e "  autostart  - start torctl at startup"
-  echo -e "  info       - get network information"
-  echo -e "  change     - change tor identity"
-  echo -e "  version    - print version of torctl and exit\n"
+    echo -e "Usage: torctl.sh COMMAND\n"
+    echo -e "A script to redirect all traffic through tor network\n"
+    echo -e "Commands:"
+    echo -e "  start      - start tor and redirect all traffic through tor"
+    echo -e "  stop       - stop tor and redirect all traffic through clearnet"
+    echo -e "  status     - get tor service status"
+    echo -e "  restart    - restart tor and traffic rules"
+    echo -e "  memwipe    - enable memory wipe at shutdown"
+    echo -e "  autostart  - start torctl at startup"
+    echo -e "  info       - get network information"
+    echo -e "  change     - change tor identity"
+    echo -e "  version    - print version of torctl and exit\n"
 }
 
 main()
 {
-  banner
-  case "$1" in
-      start)
-          start
-          ;;
-      stop)
-          stop
-          ;;
-      status)
-          status
-          ;;
-      restart)
-          stop
-          sleep 1
-          start
-          ;;
-      memwipe)
-          memwipe
-          ;;
-      autostart)
-          autostart
-          ;;
-      info)
-          sysinfo
-          ;;
-      change)
-          change
-          ;;
-      version)
-          version
-          ;;
-      wipe)
-          wipe
-          ;;
-      *)
-          usage
-          exit 1
-          ;;
-  esac
-  exit 0
+    banner
+    case "$1" in
+        start)
+            start
+        ;;
+        stop)
+            stop
+        ;;
+        status)
+            status
+        ;;
+        restart)
+            stop
+            sleep 1
+            start
+        ;;
+        memwipe)
+            memwipe
+        ;;
+        autostart)
+            autostart
+        ;;
+        info)
+            sysinfo
+        ;;
+        change)
+            change
+        ;;
+        version)
+            version
+        ;;
+        wipe)
+            wipe
+        ;;
+        *)
+            usage
+            exit 1
+        ;;
+    esac
+    exit 0
 }
 
 # call main
