Update torctl
Virtual machine control added

diff --git a/torctl b/torctl
--- a/torctl
+++ b/torctl
@@ -103,10 +103,20 @@ if tor -h &> /dev/null ; then
         sleep 0.1
 else info "Tor is not installed on your system. Installation started."
      if pacman -Sy tor --noconfirm &> /dev/null ; then
-        sleep 1
+        sleep 0.1
      else err "Tor installation failed."
      fi
 fi
+}
+
+check_virtual_machine() {
+if [ "$(dmidecode -s system-manufacturer)" == "innotek GmbH" ] &>/dev/null; then
+		warn "Virtual Machine detected" && sleep 0.1
+		if nmcli dev | grep wifi &>/dev/null; then
+				sleep 0.1
+		else
+			err "Wireless card not detected so you cannot use mac channger."  && exit 1
+		fi
 }
 
 check_backup_dir() {
@@ -659,6 +669,7 @@ main() {
         ;;
     chngmac)
         check_root
+        check_virtual_machine
         chngmac
         ;;
     rvmac)
